
package com.amx.jax.constants;

public class MessageKey
{

	public static String KEY_CIVIL_ID_VALID = "CIVIL_ID_VALID";//CIDV

	public static String KEY_CIVIL_ID_INVALID = "CIVIL_ID_INVALID";//CIDINV

	public static String KEY_CIVIL_ID_ALREADY_REGISTER = "CIVIL_ID_ALREADY_REGISTERED";//CIDAR

	public static String KEY_CIVIL_ID_NOT_REGISTERED = "CIVIL_ID_NOT_REGESTERED";//CIDNR

	public static String KEY_MOBILE_NO_ALREADY_REGISTER = "MOBILE_NUMBER_REGISTERED";//MNAR

	public static String KEY_MOBILE_NO_NOT_REGISTER = "MOBILE_NUMBER_NOT_REGISTERED";//MNNR

	public static String KEY_EMAID_INVALID = "EMAIL_ID_INVALID";//EIDINV

	public static String KEY_EMAID_VALID = "EMAIL_ID_VALID";//EIDV

	public static String KEY_EMAID_ALREADY_REGISTER = "EMAIL_ID_REGESTERED";//EMIDAR

	public static String KEY_EMAID_NOT_REGISTER = "EMAIL_ID_NOT_REGESTERED";//EMIDNR

	public static String KEY_REG_VALIDATE_OTP = "REG_VALIDATE_OTP";

	public static String KEY_CP_OTP_NOT_GENERATED = "CP_OTP_NOT_GENERATED";//CPOTPNG

	public static String KEY_VALIDATE_MOBILE_OTP = "VALIDATE_MOBILE_OTP";//VMOTP

	public static String KEY_VALIDATE_EMAIL_OTP = "VALIDATE_EMAIL_OTP";//VEOTP

	public static String KEY_MOBILE_OR_EMAIL_ALREADY_EXISTS = "MOBILE_OR_EMAIL_ALREADY_EXISTS";//MOREAE

	public static String KEY_USER_OTP_ENABLED = "USER_OTP_ENABLED";//UOTPE

	public static String KEY_USER_OTP_NOT_ENABLED = "USER_OTP_DISABLED";//UOTPNE
	
	public static String KEY_EMAIL_MOBILE_OTP_REQUIRED = "DOTP_REQUIRED";
	
	public static String KEY_EMAIL_MOBILE_OTP_REQUIRED_INVALID = "DOTP_REQUIRED_INVALID";
	
	public static String KEY_EMAIL_OTP_REQUIRED = "EOTP_REQUIRED";
	
	public static String KEY_EMAIL_OTP_REQUIRED_INVALID = "EOTP_REQUIRED_INVALID";
	
	public static String KEY_MOBILE_OTP_REQUIRED = "MOTP_REQUIRED";
	
	public static String KEY_MOBILE_OTP_REQUIRED_INVALID = "MOTP_REQUIRED_INVALID";
	
	public static String KEY_CIVIL_ID_EXPIRED = "CIVIL_ID_EXPIRED";

	public static String KEY_EMPTY_PASSWORD = "EMPTY_PASSWORD";
	
	public static String KEY_EMPTY_APPSEQUENCE_NUMBER = "EMPTY_APPSEQUENCE_NUMBER";
	
	public static String KEY_EMPTY_VEHICLE_DETAILS = "KEY_EMPTY_VEHICLE_DETAILS";
	
}

